export const interests = [
  'art',
  'books',
  'causes',
  'class',
  'comedy',
  'community',
  'conference',
  'dance',
  'food',
  'health',
  'movie',
  'music',
  'nightlife',
  'other',
  'religion',
  'shopping',
  'social',
  'sport',
  'theater',
]; //if this list changes make sure to update the styles.js to have a color for the tag
