//Events
export const SET_FETCHED_EVENTS = 'SET_FETCHED_EVENTS';

//User
export const GET_USER_LOCATIONS = 'GET_USER_LOCATIONS';
export const UPDATE_USER = 'UPDATE_USER';
export const LOG_IN = 'LOG_IN';
export const SIGN_UP = 'SIGN_UP';
export const LOG_OUT = 'LOG_OUT';
export const SAVE_FAVORITES = 'SAVE_FAVORITES';

//App
export const GET_POSSIBLE_LOCATIONS = 'GET_POSSIBLE_LOCATIONS';
export const SAVE_LOCAL_INTERESTS = 'SAVE_LOCAL_INTERESTS';
export const SAVE_START_DATE = 'SAVE_START_DATE';
export const SAVE_END_DATE = 'SAVE_END_DATE';
export const SAVE_DATE_FILTER_TYPE = 'SAVE_DATE_FILTER_TYPE';
